AWSTemplateFormatVersion: 2010-09-09
Description: >-
  allcoin-track

Transform:
  - AWS::Serverless-2016-10-31

##########################################################################
#  Globals                                                               #
##########################################################################
Globals:
  Function:
    Runtime: provided.al2
    Layers:
      - arn:aws:lambda:eu-west-3:209497400698:layer:php-80:8
    MemorySize: 128
    Timeout: 900
    Environment:
      Variables:
        APP_TIMEZONE: "Europe/Paris"
        LOG_CHANNEL: "stderr"
        AWS_DDB_TABLE_NAME: !Ref AllCoinTrackTable

##########################################################################
#  Resources                                                             #
##########################################################################
Resources:

  ##########################################################################
  #  Lambda function AssetSyncFunction                                     #
  ##########################################################################
  AssetSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AllCoinTrack-AssetSync
      Handler: public/asset_sync.php
      Description: Sync assets from Binance.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AllCoinTrackTable

  ##########################################################################
  #  Lambda function PriceSyncFunction                                     #
  ##########################################################################
  PriceSyncFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AllCoinTrack-PriceSync
      Handler: public/price_sync.php
      Description: Sync prices from Binance.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AllCoinTrackTable
      Events:
        PriceSyncScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  ##########################################################################
  #  Lambda function AssetListFunction                                     #
  ##########################################################################
  AssetListFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AllCoinTrack-AssetList
      Handler: public/asset_list.php
      Description: List all assets.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AllCoinTrackTable

  ##########################################################################
  #  Lambda function PriceSearchFunction                                   #
  ##########################################################################
  PriceSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AllCoinTrack-PriceSearch
      Handler: public/price_search.php
      Description: Search prices for an asset pair by date range.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AllCoinTrackTable

  ##########################################################################
  #  DynamoDB configuration                                                #
  ##########################################################################
  AllCoinTrackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: allcoin-track
      ProvisionedThroughput:
        ReadCapacityUnits: 20
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: lsi1
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi1
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: lsi2
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi2
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: lsi3
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi3
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: lsi4
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi4
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: lsi5
          KeySchema:
            - AttributeName: pk
              KeyType: HASH
            - AttributeName: lsi5
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: lsi1
          AttributeType: S
        - AttributeName: lsi2
          AttributeType: S
        - AttributeName: lsi3
          AttributeType: S
        - AttributeName: lsi4
          AttributeType: N
        - AttributeName: lsi5
          AttributeType: N

##########################################################################
#  Outputs                                                               #
##########################################################################
Outputs:
  AssetListFunctionName:
    Description: Asset list function name
    Value: !Ref AssetListFunction
    Export:
      Name: !Sub "${AWS::StackName}-AssetListFunctionName"
  PriceSearchFunctionName:
    Description: Price search function name
    Value: !Ref PriceSearchFunction
    Export:
      Name: !Sub "${AWS::StackName}-PriceSearchFunctionName"
